apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
  namespace: nginx
  labels:
    app: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: busybox:latest
          command: ["sh", "-c", "echo Hello from nginx job"]  # Command to be executed in the container
      restartPolicy: Never
