kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: nginx-service
spec:
  selector:
    app: nginx-service
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP