version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DB_URL=mongodb+srv://sujata:rnZzJjIDr3bIDymV@cluster0.hnn88vs.mongodb.net/

volumes:
  tasked:
