kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["", "apps", "rbac.authorization.k8s.io/v1", "batch"]
    resources: ["*"]
    verbs: ["get","apply", "list", "watch", "create", "update", "patch", "delete"]