kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager-RoleBinding
  namespace: apache
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apache-manager
subjects:
  - kind: ServiceAccount
    name: apache-sa
    namespace: apache