kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deployment
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: trainwithshubham/notes-app-k8s
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8000


