apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kunal-pod
  name: kunal-pod
spec:
  containers:
  - image: nginx:latest
    name: kunal-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "prod"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
